### ISSUE TITLE
Contact all Members / CAIP authors

### ISSUE THREAD

**Issue by ligi** [ChainAgnostic/AMS-CASA-gathering#3]

**Comment by alirezaayande** [comment]
Btc wallet:bc1qs46p47jl3v5qcsmrw8pkflz0rfcyl9p554a7f9
Ether wallet:0x4d4ba82700089953207079d8d6eE3f8249191594
I want to collect and help the people of Ukraine and the refugees from the cryptocurrencies. Please help in any way you can and teach me how to earn money and collect it so that I can help the refugees.🇺🇦🙏🇺🇦 #tanks_world Congratulations on the new app you released I wanted to know I can not make money from this github?

**Comment by bumblefudge** [comment]
@ligi Should I tag all authors in this thread, and/or should I add them all to the [github org](https://github.com/orgs/ChainAgnostic/people) which already includes about half of them? Should I also tag the authors of pending/reasonable-candidate CAIPs in the queue?
